[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "zen_garden"
authors = [
  {name = "Jacob Mannhardt", email = "jmannhardt@ethz.ch"},
  {name = "Alissa Ganter", email = "aganter@ethz.ch"}
  ]
version = "1.2.0"
description="ZEN-garden is an optimization model of energy systems and value chains."


dependencies = [
    "xarray",
    "cython",
    "pytest",
    "numpy<=1.26.4",
    "pandas",
    "geopandas",
    "scipy",
    "coverage",
    "pint",
    "matplotlib",
    "entsoe-py",
    "tables",
    "pydantic",
    "tsam",
    "h5py",
    "filelock",
    "ordered-set",
    "pyogrio",
    "psutil",
    "linopy<=0.3.10",
    "sphinx",
    "myst-parser",
    "sphinx_book_theme",
]
