name: Bump version

on:
  push:
    branches:
      - development


jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: development

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install bump2version
        run: pip install bump2version

      - name: Extract Current Version
        id: get_version
        run: |
          current_version=$(grep -oP '(?<=version = ")[^"]*' pyproject.toml)
          echo "current_version=${current_version}" >> $GITHUB_ENV

#          commits=${{join(github.event.commits.*.message, ', ') }}
#      echo $message
      - name: Check commit messages for version bump
        id: check_commits
        run: |
          message="${{ github.event.head_commit.message }}"
          if contains($message, "[patch]"); then
            bump="patch"
          elif contains($message, "[minor]"); then
            bump="minor"
          elif contains($message, "[major]"); then
            bump="major"
          else
            bump="none"
          fi
          echo "bump=$bump" >> $GITHUB_ENV
#           echo "bump=$bump"
#      - name: Bump version
#        if: env.bump != 'none'
#        run: bump2version ${{ env.bump }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Push changes
#        if: env.bump != 'none'
#        run: |
#          git push origin development --tags
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}