name: "Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    # Build the Python SDist and wheel, performs metadata and readme linting
    name: Build and verify package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2

  release:
    if: ${{ github.repository == 'ZEN-universe/ZEN-garden' }}
    name: "Create Github Release"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name : "Checkout"
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2