name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    if: ${{ github.repository == 'ZEN-universe/ZEN-garden' }}
    name: "Create Github Release"
    runs-on: ubuntu-latest
    steps:
      - name : "Checkout"
        uses: actions/checkout@v4

      - name: Set up Node.js (required for semver)
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Extract tag version
        id: extract_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "tag=$TAG" >> $GITHUB_ENV
          echo "major=$(echo $TAG | cut -d. -f1 | cut -dv -f2)" >> $GITHUB_ENV
          echo "minor=$(echo $TAG | cut -d. -f2)" >> $GITHUB_ENV
          echo "patch=$(echo $TAG | cut -d. -f3)" >> $GITHUB_ENV

      - name: Check for major/minor version
        id: check_version
        run: |
          if [[ $patch -eq 0 ]]; then
            echo "is_major_minor=true" >> $GITHUB_ENV
          else
            echo "is_major_minor=false" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        if: env.is_major_minor == 'true'
        uses: ncipollo/release-action@v2
        with:
          tag: ${{ env.tag }}
          name: ${{ env.tag }}
          commit: ${{ github.sha }}
          body: "Automated release for version ${{ env.tag }}"
          draft: false
          prerelease: false